//loaders
export const LOGIN_ENABLE_LOADER = 'LOGIN_ENABLE_LOADER';
export const LOGIN_DISABLE_LOADER = 'LOGIN_DISABLE_LOADER';

// login
export const CONTENTS_REQUEST = 'CONTENTS_REQUEST';
export const CONTENTS_RESPONSE = 'CONTENTS_RESPONSE';
export const CONTENTS_FAILED = 'CONTENTS_FAILED';
export const SEARCH_REQUEST = 'SEARCH_REQUEST';
